# Generated by Django 5.2.7 on 2025-10-18 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItemAddOn',
        ),
    ]
