# Generated by Django 5.2.6 on 2025-09-27 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Canteen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('add_on_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Canteen.canteen')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_stock', models.IntegerField()),
                ('threshold_level', models.IntegerField()),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemAddOn',
            fields=[
                ('menu_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_optional', models.BooleanField(null=True)),
                ('add_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.addon')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemCategories',
            fields=[
                ('menu_item_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.category')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.menuitem')),
            ],
        ),
    ]
