# Generated by Django 5.2.7 on 2025-10-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_remove_cartitem_menu_item_delete_cartitemaddon'),
        ('Menu', '0001_initial'),
        ('Order', '0002_delete_orderitemaddon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemaddon',
            name='add_on',
        ),
        migrations.RemoveField(
            model_name='menuitemaddon',
            name='menu_id',
        ),
        migrations.RemoveField(
            model_name='menuitemcategories',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='menuitemcategories',
            name='menu_id',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='categories',
            field=models.ManyToManyField(related_name='menu_items', to='Menu.category'),
        ),
        migrations.DeleteModel(
            name='AddOn',
        ),
        migrations.DeleteModel(
            name='MenuItemAddOn',
        ),
        migrations.DeleteModel(
            name='MenuItemCategories',
        ),
    ]
