# Generated by Django 5.2.7 on 2025-10-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_remove_menuitemaddon_add_on_and_more'),
        ('Promo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='promocategory',
            name='promo',
        ),
        migrations.RemoveField(
            model_name='promoitem',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='promoitem',
            name='promo',
        ),
        migrations.AddField(
            model_name='promoname',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, related_name='promos', to='Menu.category'),
        ),
        migrations.AddField(
            model_name='promoname',
            name='applicable_items',
            field=models.ManyToManyField(blank=True, related_name='promos', to='Menu.menuitem'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='PromoCategory',
        ),
        migrations.DeleteModel(
            name='PromoItem',
        ),
    ]
